version: '2'
services:
  # web service
  web:
    build: .  # use the dockerfile to build our image
    command: npm start # start the application
    volumes:
      # mount paths between the host and the container
      - .:/usr/app/ # mount the root directory to our working directory inside the container
      - /usr/app/node_modules # mount the buildtime node_modules directory to the host machine
    expose:
      - 80
    depends_on:
      - postgres
    # set some envvars
    environment:
      VIRTUAL_HOST: goodjob.app
      VIRTUAL_PORT:  8080
      PORT: 80
      DATABASE_URL: postgres://goodjob@postgres/goodjob
    container_name: good_job_app
  # database service
  postgres:
    # image lets us specify a prebuilt image to use
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: goodjobapp
      POSTGRES_DB: goodjob
      POSTGRES_PASSWORD: 'yeeeeew'

# specify the network to use
networks:
  default:
    external:
      name: nginx-proxy
